FROM golang:1.8.1-alpine

RUN apk add --no-cache make git

RUN go get -u github.com/golang/lint/golint &&\
	go get -u github.com/gordonklaus/ineffassign &&\
	go get -u github.com/LK4D4/vndr

WORKDIR /go/src/github.com/linuxkit/rtf

COPY . ./

VOLUME [ "/go/src/github.com/linuxkit/rtf/_build" ]

CMD make
